version: 0.0
os: linux

files:
  - source: build/libs/subsubclipclop-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user/app/build/libs

  - source: scripts/
    destination: /home/ec2-user/app/scripts

  - source: .env
    destination: /home/ec2-user/app

  - source: appspec.yml
    destination: /home/ec2-user/app

hooks:
  AfterInstall:
    - location: scripts/chmod.sh
      timeout: 30
      runas: root
    - location: scripts/start.sh
      timeout: 60
      runas: ec2-user
